### PR TITLE
Shinichi test

### PR DESCRIPTION
**Pull request by itchyshin**

### CODE REVIEW

**Comment by itchyshin** [comment]
@roseodea - just testing - the first draft is done - more to do but it knitted.

**Review by roseodea — APPROVED** [review]

**Comment by roseodea** [comment]
Screen Shot 2021-04-08 at 3 53 41 pm
@itchyshin doesn't knit for me -- error at line 705

**Comment by itchyshin** [comment]
@roseodea - you probably need to install a development latest version of emmeans

remotes::install_github("rvlenth/emmeans", dependencies = TRUE, build_opts = "")

as he just make it work for metafor.

**Comment by roseodea** [comment]
> @roseodea - you probably need to install a development latest version of emmeans
> 
> remotes::install_github("rvlenth/emmeans", dependencies = TRUE, build_opts = "")
> 
> as he just made it work for metafor.

Had to update 'all' packages alongside of it (failed to install otherwise), but it knits for me now 👍

**Comment by itchyshin** [comment]
@roseodea - great - can I merge it now? - once merged, I will submit the MS. I know there are a lot more little improvements we can do for the appendix but we can do this after submission.

**Comment by itchyshin** [comment]
@roseodea - I see you approved the changes so I have merged - thanks

**Pull request merged**
